### ISSUE TITLE
Add Hedge Capability To Liquidator

### ISSUE THREAD

**Issue by djphillyg** [dydxprotocol/liquidator#11]
Create a feature that will allow the bot to hedge the funds that are immediately liquidated in a DEX to allow for arbitrage opportunities with an eased requirement of capital

**Comment by ameenpv** [comment]
Second this.

**Comment by AntonioJuliano** [comment]
Part of https://github.com/dydxprotocol/issues/issues/157

**Comment by AntonioJuliano** [comment]
Specifically let's start with atomic hedging of WETH-DAI liquidations on eth2dai

**Comment by BrendanChou** [comment]
Moved to BAC-26
