### ISSUE TITLE
Add GAS_ADDITION

### ISSUE THREAD

**Issue by BrendanChou** [dydxprotocol/liquidator#13]
Right now we just multiply the gas price value from EthGasStation, but we should also allow a flat addition

**Comment by AntonioJuliano** [comment]
Part of https://github.com/dydxprotocol/issues/issues/157

**Comment by WyseNynja** [comment]
@AntonioJuliano I get a 404 on that link. Is that a private repo?

**Comment by pereztechseattle** [comment]
Done! :)

**Comment by BrendanChou** [comment]
Fixed by #29 , thanks @pereztechseattle !
