### ISSUE TITLE
MIN_VALUE_LIQUIDATED checks minimum value attempting to liquidate, not actual amount liquidated

### ISSUE THREAD

**Issue by BrendanChou** [dydxprotocol/liquidator#15]

**Comment by andrei-anisimov** [comment]
@BrendanChou Is this related to the following error?

![image](https://user-images.githubusercontent.com/1471231/65571574-035bc380-df1a-11e9-8520-14aa5e7ef17e.png)

**Comment by BrendanChou** [comment]
Related, but that error usually means that someone got to the liquidation before you did

**Comment by andrei-anisimov** [comment]
Ah, got it. I get lots of those. I’m assuming that’s because their gas price is higher or they’re polling more frequently, correct?

**Comment by AntonioJuliano** [comment]
Part of https://github.com/dydxprotocol/issues/issues/157

**Comment by BrendanChou** [comment]
Will-not-change behavior but changed envvar name to `SOLO_MIN_OVERHEAD_VALUE` for clarity
