### ISSUE TITLE
"Owner private key does not match address"

### ISSUE THREAD

**Issue by pereztechseattle** [dydxprotocol/liquidator#27]
When starting the app, I get the error "Owner private key does not match address".   I'm using my Metamask address and private key.  (yes, I've triple checked everything)  The account is also funded (with a little ETH) on dxdy.

What's wrong?

**Comment by michaeldim** [comment]
If you are setting your address & key in the env file then you need to rebuild the docker image before running the container with your settings.

**Comment by pereztechseattle** [comment]
Found the problem.  A '0x' is required before the private key.

**Comment by pereztechseattle** [comment]
FYI, I'm running the app straight from npm which is a bit easier, and I can step thru the code.

**Comment by JimLynchCodes** [comment]
@michaeldim - how does one "rebuild the docker image"?

I'm using the project straight from docker:
```
docker run \
  -e WALLET_ADDRESS=0xe8f9A288554FAAbBAca8c6946bF2E3A07B685c12 \
  -e WALLET_PRIVATE_KEY=fc23f0c104eb61b5ef060cefef52a197ca67629b09393aa35199fbe4a77b7e9a \
  -e ETHEREUM_NODE_URL=https://mainnet.infura.io/v3/8bca68ce47d04063832a7c91509653af \
  -e SOLO_LIQUIDATIONS_ENABLED=true \
  -e PERP_LIQUIDATIONS_ENABLED=true \
  -e SOLO_EXPIRATIONS_ENABLED=false \
  -e SOLO_MIN_ACCOUNT_COLLATERALIZATION=0.5 \
  -e PERP_MIN_ACCOUNT_COLLATERALIZATION=0.5 \
  dydxprotocol/liquidator
```
