### ISSUE TITLE
What can I expect with this software?

### ISSUE THREAD

**Issue by pereztechseattle** [dydxprotocol/liquidator#28]
I've had the liquidator running for over 24 hours now, with the following throttle env vars:

ACCOUNT_POLL_INTERVAL_MS=4000
MARKET_POLL_INTERVAL_MS=4000
SOLO_LIQUIDATE_POLL_INTERVAL_MS=4000

(I changed the default 5 seconds to 4).

And after 24 hours, nothing.  No liquidations.  No accounts found NEEDING liquidation.  Bupkis.

Is this normal?

**Comment by michaeldim** [comment]
This is normal. It will only attempt to liquidate accounts that are under collaterized (<115%).

**Comment by pereztechseattle** [comment]
Yes, I get that.  I guess I'm asking how many undercollaterized accounts I can expect the liquidator to find in a typical day/week/whatever?  Is zero normal?  Is 10 normal?  10,000?  

Thanks.

**Comment by michaeldim** [comment]
It can go several weeks without liquidating one account and then you can have multiples go at once.  Look at the contract called by the bot to see how often liquidations take place roughly : https://etherscan.io/address/0xd4b6cd147ad8a0d5376b6fdba85fe8128c6f0686. 

Bear in mind you will be competing with others running the bot with large balances 1 mil + that use high gas price to win the liquidations, a lot of which are uneconomical but make up for it on the large account liquidations.

**Comment by pereztechseattle** [comment]
Good tip, thanks!  I assume all the failed transactions are liquidators getting beaten to the punch.

Thanks again!
