### ISSUE TITLE
LIQUIDATOR_ACCOUNT_OWNER not authenticating 

### ISSUE THREAD

**Issue by twhitinger** [dydxprotocol/liquidator#4]
I am trying to set up the liquidator bot, when I pass in the correct Ethereum address/private key combination I keep getting an authentication error generated from file:

<https://github.com/dydxprotocol/liquidator/blob/a95ee70864507644257789079bb14ab7c2562349/src/helpers/solo.js#L10>

The liquidatorAccount variable and liquidatorAccount.address which is returned from the loadAccounts function generates a completely different address that has no match on etherscan and is obviously has no balance and is stored in the liquidatorAccount.address. Which doesn't match process.env.LIQUIDATOR_ACCOUNT_OWNER I am passing in.  

I've tried multiple wallet addresses and they continue to follow the pattern with a dummy liquidatorAccount.address being generated. Please advise if you are able to reproduce or any ideas why this might be occurring.

Thanks,

**Comment by michaeldim** [comment]
Are you setting your LIQUIDATOR_ACCOUNT_OWNER in the .env file? If so you need to rebuild the docker image to copy the new values across.

**Comment by BrendanChou** [comment]
Please reopen if still an issue on the latest version
